import { it, expect } from 'vitest'
import * as V from './vocabulary.js'
import { DebugParser } from '../types.js'
import { DebugMove } from '../debug.js'


it('checkRank', () => {
    const position = DebugParser.Position(`
........
........
....k...
........
........
.Q......
......R.
........
 `.trim())

    let result = V.checkRank(position)

    expect(result.length).toBe(2)
    expect(DebugMove.San(position, result[0])).toBe('Rg6+')
    expect(DebugMove.San(position, result[1])).toBe('Qb6+')
})


it('kingEvadeSafe', () => {
    const position = DebugParser.Position(`
........
........
.q..K...
........
........
.....r..
........
........
 `.trim())

    let result = V.kingEvadeSafe(position)

    expect(result.length).toBe(4)
    expect(DebugMove.San(position, result[0])).toBe('Kd5')
    expect(DebugMove.San(position, result[1])).toBe('Ke5')
    expect(DebugMove.San(position, result[2])).toBe('Kd7')
    expect(DebugMove.San(position, result[3])).toBe('Ke7')
})


it('isCheck', () => {
    let position = DebugParser.Position(`
........
........
.q..K...
........
........
.....r..
........
........
 `.trim())

    expect(V.isCheck(position)).toBe(true)

    position = DebugParser.Position(`
........
........
.q.pK...
........
........
.....r..
........
........
 `.trim())

    expect(V.isCheck(position)).toBe(false)
})