import { expect, it } from 'vitest'

import { Bitboard, Debug, Fen, Uci } from './types'


it('works', () => {

    expect(Debug.Bitboard(Bitboard.A1)).toEqual(`
........
........
........
........
........
........
........
o.......
`.trim())

    expect(Debug.Bitboard(Bitboard.H8.bitor(Bitboard.D4))).toEqual(`
.......o
........
........
........
...o....
........
........
........
`.trim())

})


it('position', () => {
    expect(Debug.Position(Fen.InitialPosition)).toEqual(`
rnbqkbnr
pppppppp
........
........
........
........
PPPPPPPP
RNBQKBNR
`.trim())

    const position = Fen.InitialPosition

    position.makeMove(Uci.parse('e2e4', position))
    position.makeMove(Uci.parse('e7e5', position))
    position.makeMove(Uci.parse('g1f3', position))
    position.makeMove(Uci.parse('b8c6', position))

    expect(Debug.Position(position)).toEqual(`
r.bqkbnr
pppp.ppp
..n.....
....p...
....P...
.....N..
PPPP.PPP
RNBQKB.R
`.trim())

})